[package]
name = "abntypst"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = ["Gabriel Malosto <professional@gabdumal.com>"]
license = "AGPL-3.0"
description = "A template for creating documents accordingly to ABNT."
repository = "https://github.com/gabdumal/abntypst"
